# Generated by Django 3.1.6 on 2021-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
