# Generated by Django 3.1.6 on 2021-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
